#!/usr/bin/env python3
"""Write data/packs/core/careers.json from compact tuples (migrated from legacy WFRP.py, typos fixed)."""
from __future__ import annotations

import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "data", "packs", "core", "careers.json")

# (advance_chars_csv, skills8, talents4_csv, trappings, status)
C: dict[str, tuple[str, list[str], str, str, str]] = {
    "Apothecary": (
        "T,Dex,Int",
        [
            "Consume Alcohol",
            "Heal",
            "Language (Classical)",
            "Lore (Chemistry)",
            "Lore (Medicine)",
            "Lore (Plants)",
            "Trade (Apothecary)",
            "Trade (Poisoner)",
        ],
        "Concoct, Craftsman (Apothecary), Etiquette (Scholar), Read/Write",
        "Book (Blank), Healing Draft, Leather Jerkin, Pestle and Mortar",
        "Apothecary's Apprentice — Brass 3",
    ),
    "Engineer": (
        "BS,Dex,Int",
        [
            "Consume Alcohol",
            "Cool",
            "Endurance",
            "Language (Classical)",
            "Lore (Engineer)",
            "Perception",
            "Ranged (Blackpowder)",
            "Trade (Engineer)",
        ],
        "Artist, Gunner, Read/Write, Tinker",
        "Book (Engineer), Hammer and Spikes",
        "Student Engineer — Brass 4",
    ),
    "Lawyer": (
        "I,Dex,Int",
        [
            "Consume Alcohol",
            "Endurance",
            "Haggle",
            "Language (Classical)",
            "Lore (Law)",
            "Lore (Theology)",
            "Perception",
            "Research",
        ],
        "Blather, Etiquette (Scholar), Read/Write, Speedreader",
        "Book (Law), Magnifying Glass",
        "Student Lawyer — Brass 4",
    ),
    "Nun": (
        "Dex,Int,Fel",
        [
            "Art (Calligraphy)",
            "Cool",
            "Endurance",
            "Entertain (Storytelling)",
            "Gossip",
            "Heal",
            "Lore (Theology)",
            "Pray",
        ],
        "Bless (Any), Stone Soup, Panhandle, Read/Write",
        "Religious Symbol, Robes",
        "Novitiate — Brass 1",
    ),
    "Physician": (
        "Dex,Int,WP",
        [
            "Bribery",
            "Cool",
            "Drive",
            "Endurance",
            "Gossip",
            "Heal",
            "Perception",
            "Sleight of Hand",
        ],
        "Bookish, Field Dressing, Read/Write, Strike to Stun",
        "Bandages, Healing Draught",
        "Physician's Apprentice — Brass 4",
    ),
    "Priest": (
        "T,Ag,WP",
        [
            "Athletics",
            "Cool",
            "Endurance",
            "Intuition",
            "Lore (Theology)",
            "Perception",
            "Pray",
            "Research",
        ],
        "Bless (Any), Holy Visions, Read/Write, Suave",
        "Religious Symbol, Robes",
        "Initiate — Brass 2",
    ),
    "Scholar": (
        "T,Int,WP",
        [
            "Consume Alcohol",
            "Entertain (Storytelling)",
            "Gamble",
            "Gossip",
            "Haggle",
            "Language (Classical)",
            "Lore (Any)",
            "Research",
        ],
        "Carouser, Read/Write, Savvy, Super Numerate",
        "Alcohol, Book, Opinions, Writing Kit",
        "Student — Brass 3",
    ),
    "Wizard": (
        "WS,Int,WP",
        [
            "Channelling (Any Colour)",
            "Dodge",
            "Intuition",
            "Language (Magick)",
            "Lore (Magic)",
            "Melee (Basic)",
            "Melee (Polearm)",
            "Perception",
        ],
        "Aethyric Attunement, Petty Magic (Any), Read/Write, Second Sight",
        "Grimoire, Staff",
        "Wizard's Apprentice — Brass 3",
    ),
    "Agitator": (
        "BS,Int,Fel",
        [
            "Art (Writing)",
            "Bribery",
            "Charm",
            "Consume Alcohol",
            "Gossip",
            "Haggle",
            "Lore (Politics)",
            "Trade (Printing)",
        ],
        "Blather, Gregarious, Panhandle, Read/Write",
        "Writing Kit, Hammer and Nails, Pile of Leaflets",
        "Pamphleteer — Brass 1",
    ),
    "Artisan": (
        "S,T,Dex",
        [
            "Athletics",
            "Cool",
            "Consume Alcohol",
            "Dodge",
            "Endurance",
            "Evaluate",
            "Stealth (Urban)",
            "Trade (Any)",
        ],
        "Artistic, Craftsman (Any), Strong Back, Very Strong",
        "Chalk, Leather Jerkin, 1d10 rags",
        "Apprentice Artisan — Brass 2",
    ),
    "Beggar": (
        "T,Ag,Fel",
        [
            "Athletics",
            "Charm",
            "Consume Alcohol",
            "Cool",
            "Dodge",
            "Endurance",
            "Intuition",
            "Stealth (Urban)",
        ],
        "Panhandle, Resistance (Disease), Stone Soup, Very Resilient",
        "Poor Quality Blanket, Cup",
        "Pauper — Brass 0",
    ),
    "Investigator": (
        "I,Ag,Int",
        [
            "Charm",
            "Climb",
            "Cool",
            "Gossip",
            "Intuition",
            "Perception",
            "Stealth (Urban)",
            "Track",
        ],
        "Alley Cat, Beneath Notice, Read/Write, Sharp",
        "Lantern, Lamp Oil, Journal, Quill and Ink",
        "Sleuth — Silver 1",
    ),
    "Merchant": (
        "WS,Ag,Fel",
        [
            "Animal Care",
            "Bribery",
            "Charm",
            "Consume Alcohol",
            "Drive",
            "Gamble",
            "Gossip",
            "Haggle",
        ],
        "Blather, Dealmaker, Read/Write, Suave",
        "Abacus, Mule and Cart, Canvas Tarpaulin, 3d10 Silver Shillings",
        "Trader — Silver 2",
    ),
    "Rat Catcher": (
        "WS,BS,WP",
        [
            "Athletics",
            "Animal Training (Dog)",
            "Charm Animal",
            "Consume Alcohol",
            "Endurance",
            "Melee (Basic)",
            "Ranged (Sling)",
            "Stealth (Underground or Urban)",
        ],
        "Night Vision, Resistance (Disease), Strike Mighty Blow, Strike to Stun",
        "Sling with Ammunition, Sack, Small but Vicious Dog",
        "Rat Hunter — Brass 3",
    ),
    "Townsman": (
        "Ag,Int,Fel",
        [
            "Charm",
            "Climb",
            "Consume Alcohol",
            "Drive",
            "Dodge",
            "Gamble",
            "Gossip",
            "Haggle",
        ],
        "Alley Cat, Beneath Notice, Etiquette (Servants), Sturdy",
        "Lodgings, Sturdy Boots",
        "Clerk — Silver 1",
    ),
    "Watchman": (
        "WS,S,Fel",
        [
            "Athletics",
            "Climb",
            "Consume Alcohol",
            "Dodge",
            "Endurance",
            "Gamble",
            "Melee (Basic)",
            "Perception",
        ],
        "Drilled, Hardy, Strike to Stun, Tenacious",
        "Hand Weapon, Leather Jack, Uniform",
        "Watchman — Silver 1",
    ),
    "Advisor": (
        "T,I,Ag",
        [
            "Bribery",
            "Consume Alcohol",
            "Endurance",
            "Gossip",
            "Haggle",
            "Language (Classical)",
            "Lore (Politics)",
            "Perception",
        ],
        "Beneath Notice, Etiquette (Any), Gregarious, Read/Write",
        "Writing Kit",
        "Aide — Silver 2",
    ),
    "Artist": (
        "S,I,Dex",
        [
            "Art (Any)",
            "Cool",
            "Consume Alcohol",
            "Evaluate",
            "Endurance",
            "Gossip",
            "Perception",
            "Stealth (Urban)",
        ],
        "Artistic, Sharp, Strong Back, Tenacious",
        "Brush or Chisel or Quill Pen",
        "Apprentice Artist — Silver 1",
    ),
    "Duellist": (
        "WS,I,Ag",
        [
            "Athletics",
            "Dodge",
            "Endurance",
            "Heal",
            "Intuition",
            "Language (Classical)",
            "Melee (Any)",
            "Perception",
        ],
        "Beat Blade, Distract, Feint, Step Aside",
        "Basic Weapon or Rapier, Sling Bag containing Clothing and 1d10 Bandages",
        "Fencer — Silver 3",
    ),
    "Envoy": (
        "T,Ag,Fel",
        [
            "Athletics",
            "Charm",
            "Drive",
            "Dodge",
            "Endurance",
            "Intuition",
            "Ride (Horse)",
            "Row",
        ],
        "Blather, Etiquette (Nobles), Read/Write, Suave",
        "Leather Jack, Livery, Scroll Case",
        "Herald — Silver 2",
    ),
    "Noble": (
        "WS,I,Dex",
        [
            "Bribery",
            "Consume Alcohol",
            "Gamble",
            "Intimidate",
            "Leadership",
            "Lore (Heraldry)",
            "Melee (Fencing)",
            "Play (Any)",
        ],
        "Etiquette (Nobles), Luck, Noble Blood, Read/Write",
        "Courtly Garb, Foil or Hand Mirror, Jewellery",
        "Scion — Gold 1",
    ),
    "Servant": (
        "S,T,Ag",
        [
            "Athletics",
            "Climb",
            "Drive",
            "Dodge",
            "Endurance",
            "Intuition",
            "Perception",
            "Stealth (Any)",
        ],
        "Beneath Notice, Strong Back, Strong-minded, Sturdy",
        "Floor Brush",
        "Menial — Silver 1",
    ),
    "Spy": (
        "Ag,WP,Fel",
        [
            "Bribery",
            "Charm",
            "Cool",
            "Gamble",
            "Gossip",
            "Haggle",
            "Perception",
            "Stealth (Any)",
        ],
        "Blather, Carouser, Gregarious, Shadow",
        "Charcoal stick, Sling Bag containing 2 different sets of clothing and Hooded Cloak",
        "Informer — Brass 3",
    ),
    "Warden": (
        "S,T,WP",
        [
            "Athletics",
            "Charm Animal",
            "Consume Alcohol",
            "Cool",
            "Endurance",
            "Intuition",
            "Perception",
            "Trade (Any)",
        ],
        "Menacing, Night Vision, Sharp, Strike to Stun",
        "Keys, Lantern, Lamp Oil, Livery",
        "Custodian — Silver 1",
    ),
    "Bailiff": (
        "WS,I,WP",
        [
            "Cool",
            "Dodge",
            "Endurance",
            "Gossip",
            "Haggle",
            "Intimidate",
            "Melee (Basic)",
            "Perception",
        ],
        "Embezzle, Numismatics, Strong Back, Tenacious",
        "Hand weapon, small lock box",
        "Tax Collector — Silver 1",
    ),
    "Hedge Witch": (
        "T,I,Dex",
        [
            "Channelling",
            "Endurance",
            "Intuition",
            "Lore (Folklore)",
            "Lore (Herbs)",
            "Outdoor Survival",
            "Perception",
            "Trade (Charms)",
        ],
        "Fast Hands, Petty Magic, Rover, Strider (Woodlands)",
        "1d10 Lucky Charms, Quarterstaff, Backpack",
        "Hedge Apprentice — Brass 1",
    ),
    "Herbalist": (
        "T,I,Ag",
        [
            "Charm Animal",
            "Climb",
            "Endurance",
            "Lore (Herbs)",
            "Outdoor Survival",
            "Perception",
            "Swim",
            "Trade (Herbalist)",
        ],
        "Acute Sense (Taste), Orientation, Rover, Strider (Any)",
        "Boots, Cloak, Sling Bag containing Assortment of Herbs",
        "Herb Gatherer — Brass 2",
    ),
    "Hunter": (
        "S,T,Int",
        [
            "Charm Animal",
            "Climb",
            "Endurance",
            "Lore (Beasts)",
            "Outdoor Survival",
            "Perception",
            "Ranged (Bow)",
            "Set Trap",
        ],
        "Hardy, Rover, Strider (Any), Trapper",
        "Selection of Animal Traps, Hand Weapon, Sturdy Boots and Cloak",
        "Trapper — Brass 2",
    ),
    "Miner": (
        "S,T,WP",
        [
            "Cool",
            "Endurance",
            "Intuition",
            "Lore (Local)",
            "Melee (Two-handed)",
            "Outdoor Survival",
            "Perception",
            "Swim",
        ],
        "Rover, Strider (Rocky), Sturdy, Tenacious",
        "Charcoal Stick, Crude Map, Pan, Spade",
        "Prospector — Brass 2",
    ),
    "Mystic": (
        "I,Dex,Fel",
        [
            "Charm",
            "Entertain (Fortune Telling)",
            "Dodge",
            "Gossip",
            "Haggle",
            "Intuition",
            "Perception",
            "Sleight of Hand",
        ],
        "Attractive, Luck, Second Sight, Suave",
        "Deck of Cards or Dice, Cheap Jewellery",
        "Fortune Teller — Brass 1",
    ),
    "Scout": (
        "T,I,Ag",
        [
            "Charm Animal",
            "Climb",
            "Endurance",
            "Gossip",
            "Lore (Local)",
            "Melee (Basic)",
            "Outdoor Survival",
            "Perception",
        ],
        "Orientation, Rover, Sharp, Strider (Any)",
        "Hand Weapon, Leather Jack, Sturdy Boots and Cloak, Rope",
        "Guide — Brass 3",
    ),
    "Villager": (
        "S,T,Ag",
        [
            "Animal Care",
            "Athletics",
            "Consume Alcohol",
            "Endurance",
            "Gossip",
            "Melee (Fist)",
            "Lore (Local)",
            "Outdoor Survival",
        ],
        "Rover, Strong Back, Strong-minded, Stone Soup",
        "None",
        "Peasant — Brass 2",
    ),
    "Bounty Hunter": (
        "WS,T,Ag",
        [
            "Bribery",
            "Charm",
            "Gossip",
            "Haggle",
            "Intuition",
            "Melee (Basic)",
            "Outdoor Survival",
            "Perception",
        ],
        "Break and Enter, Shadow, Strike to Stun, Suave",
        "Hand Weapon, Leather Jerkin, Rope",
        "Thief-taker — Silver 1",
    ),
    "Coachman": (
        "BS,T,WP",
        [
            "Animal Care",
            "Charm Animal",
            "Climb",
            "Drive",
            "Endurance",
            "Perception",
            "Ranged (Entangling)",
            "Ride (Horse)",
        ],
        "Animal Affinity, Seasoned Traveller, Trick-Riding, Tenacious",
        "Warm Coat and Gloves, Whip",
        "Postilion — Silver 1",
    ),
    "Entertainer": (
        "Ag,Dex,Fel",
        [
            "Athletics",
            "Charm",
            "Entertain (Any)",
            "Gossip",
            "Haggle",
            "Perform (Any)",
            "Play (Any)",
            "Sleight of Hand",
        ],
        "Attractive, Mimic, Public Speaking, Suave",
        "Bowl, Instrument",
        "Busker — Brass 3",
    ),
    "Flagellant": (
        "WP,S,T",
        [
            "Dodge",
            "Endurance",
            "Heal",
            "Intimidate",
            "Intuition",
            "Lore (Theology)",
            "Melee (Flail)",
            "Outdoor Survival",
        ],
        "Berserk Charge, Frenzy, Read/Write, Stone Soup",
        "Flail, Tattered Robes",
        "Zealot — Brass 0",
    ),
    "Messenger": (
        "T,I,Ag",
        [
            "Athletics",
            "Climb",
            "Dodge",
            "Endurance",
            "Gossip",
            "Navigation",
            "Perception",
            "Melee (Fist)",
        ],
        "Flee!, Fleet Footed, Sprinter, Step Aside",
        "Scroll Case",
        "Runner — Brass 3",
    ),
    "Pedlar": (
        "T,Dex,WP",
        [
            "Charm",
            "Endurance",
            "Entertain (Storytelling)",
            "Gossip",
            "Haggle",
            "Intuition",
            "Outdoor Survival",
            "Stealth (Rural or Urban)",
        ],
        "Fisherman, Flee!, Rover, Tinker",
        "Backpack, Bedroll, Goods worth 2d10 brass, Tent",
        "Vagabond — Brass 1",
    ),
    "Road Warden": (
        "BS,T,I",
        [
            "Bribery",
            "Consume Alcohol",
            "Gamble",
            "Gossip",
            "Haggle",
            "Melee (Basic)",
            "Perception",
            "Ranged (Crossbow)",
        ],
        "Coolheaded, Embezzle, Marksman, Numismatics",
        "Crossbow with 10 Bolts, Leather Jack",
        "Toll Keeper — Brass 5",
    ),
    "Witch Hunter": (
        "T,I,WP",
        [
            "Charm",
            "Consume Alcohol",
            "Heal",
            "Intimidate",
            "Intuition",
            "Lore (Torture)",
            "Melee (Basic)",
            "Perception",
        ],
        "Coolheaded, Menacing, Read/Write, Resolute",
        "Hand Weapon, Instruments of Torture",
        "Interrogator — Silver 1",
    ),
    "Boatman": (
        "S,T,Ag",
        [
            "Consume Alcohol",
            "Dodge",
            "Endurance",
            "Gossip",
            "Melee (Basic)",
            "Row",
            "Sail",
            "Swim",
        ],
        "Dirty Fighting, Fisherman, Strong Back, Strong Swimmer",
        "Hand Weapon (Boat Hook), Leather Jack, Pole",
        "Boat-hand — Silver 1",
    ),
    "Huffer": (
        "WS,T,I",
        [
            "Consume Alcohol",
            "Gossip",
            "Intuition",
            "Lore (Local)",
            "Lore (Riverways)",
            "Perception",
            "Row",
            "Swim",
        ],
        "Fisherman, Night Vision, Orientation, Waterman",
        "Hand Weapon (Boat Hook), Storm Lantern and Oil",
        "Riverguide — Brass 4",
    ),
    "Riverwoman": (
        "T,Ag,Dex",
        [
            "Athletics",
            "Consume Alcohol",
            "Dodge",
            "Endurance",
            "Gossip",
            "Outdoor Survival",
            "Row",
            "Swim",
        ],
        "Fisherman, Gregarious, Strider (Marshes), Strong Swimmer",
        "Bucket, Fishing Rod and Bait, Leather Leggings",
        "Greenfish — Brass 2",
    ),
    "Riverwarden": (
        "BS,S,Fel",
        [
            "Athletics",
            "Dodge",
            "Endurance",
            "Melee (Basic)",
            "Perception",
            "Row",
            "Sail",
            "Swim",
        ],
        "Strong Swimmer, Strong Back, Very Strong, Waterman",
        "Hand Weapon (Sword), Leather Jack, Uniform",
        "River Recruit — Silver 1",
    ),
    "Seaman": (
        "Ag,Dex,Fel",
        [
            "Climb",
            "Consume Alcohol",
            "Gamble",
            "Gossip",
            "Row",
            "Melee (Fist)",
            "Sail",
            "Swim",
        ],
        "Fisherman, Strider (Coastal), Strong Back, Strong Swimmer",
        "Bucket, Brush, Mop",
        "Landsman — Silver 1",
    ),
    "Smuggler": (
        "Ag,Dex,WP",
        [
            "Athletics",
            "Bribery",
            "Cool",
            "Consume Alcohol",
            "Row",
            "Sail",
            "Stealth (Rural or Urban)",
            "Swim",
        ],
        "Criminal, Fisherman, Strider (Marshes), Strong Back",
        "Large Sack, Mask or Scarves, Tinderbox, Storm Lantern and Oil",
        "River Runner — Brass 2",
    ),
    "Stevedore": (
        "WS,T,I",
        [
            "Athletics",
            "Climb",
            "Consume Alcohol",
            "Dodge",
            "Endurance",
            "Gossip",
            "Melee (Basic)",
            "Swim",
        ],
        "Dirty Fighting, Strong Back, Sturdy, Very Strong",
        "Hand Weapon (Boat Hook), Leather Gloves",
        "Dockhand — Brass 3",
    ),
    "Wrecker": (
        "WS,S,I",
        [
            "Climb",
            "Consume Alcohol",
            "Dodge",
            "Endurance",
            "Row",
            "Melee (Basic)",
            "Outdoor Survival",
            "Swim",
        ],
        "Break and Enter, Criminal, Fisherman, Strong Back",
        "Crowbar, Large Sack, Leather Gloves",
        "Cargo Scavenger — Brass 2",
    ),
    "Bawd": (
        "Ag,Dex,Fel",
        [
            "Bribery",
            "Charm",
            "Consume Alcohol",
            "Entertain (Any)",
            "Gamble",
            "Gossip",
            "Haggle",
            "Intimidate",
        ],
        "Attractive, Alley Cat, Blather, Gregarious",
        "Flask of Spirits",
        "Hustler — Brass 1",
    ),
    "Charlatan": (
        "I,Ag,Fel",
        [
            "Bribery",
            "Consume Alcohol",
            "Charm",
            "Entertain (Storytelling)",
            "Gamble",
            "Gossip",
            "Haggle",
            "Sleight of Hand",
        ],
        "Cardsharp, Diceman, Etiquette (Any), Luck",
        "Backpack, 2 Sets Clothing, Deck of Cards, Dice",
        "Swindler — Brass 3",
    ),
    "Fence": (
        "I,Ag,Fel",
        [
            "Charm",
            "Dodge",
            "Evaluate",
            "Gamble",
            "Gossip",
            "Haggle",
            "Intuition",
            "Melee (Basic)",
        ],
        "Alley Cat, Cardsharp, Dealmaker, Gregarious",
        "Hand Weapon, Stolen Goods worth 3d10 Shillings",
        "Broker — Silver 1",
    ),
    "Grave Robber": (
        "S,I,WP",
        [
            "Climb",
            "Cool",
            "Dodge",
            "Endurance",
            "Gossip",
            "Intuition",
            "Perception",
            "Stealth (Any)",
        ],
        "Alley Cat, Criminal, Flee!, Strong Back",
        "Crowbar, Handcart, Hooded Cloak, Tarpaulin",
        "Body Snatcher — Brass 2",
    ),
    "Outlaw": (
        "WS,S,T",
        [
            "Athletics",
            "Consume Alcohol",
            "Cool",
            "Endurance",
            "Gamble",
            "Intimidate",
            "Melee (Basic)",
            "Outdoor Survival",
        ],
        "Combat Aware, Criminal, Rover, Flee!",
        "Bedroll, Hand Weapon, Leather Jerkin, Tinderbox",
        "Brigand — Brass 1",
    ),
    "Racketeer": (
        "WS,S,T",
        [
            "Consume Alcohol",
            "Cool",
            "Dodge",
            "Endurance",
            "Intimidate",
            "Lore (Local)",
            "Melee (Fist)",
            "Stealth (Urban)",
        ],
        "Criminal, Etiquette (Criminals), Menacing, Strike Mighty Blow",
        "Brass Knuckles, Leather Jack",
        "Thug — Brass 3",
    ),
    "Thief": (
        "I,Ag,WP",
        [
            "Athletics",
            "Climb",
            "Cool",
            "Dodge",
            "Endurance",
            "Intuition",
            "Perception",
            "Stealth (Urban)",
        ],
        "Alley Cat, Criminal, Etiquette (Criminals), Flee!",
        "Crowbar, Leather Jerkin, Sack",
        "Prowler — Brass 1",
    ),
    "Witch": (
        "WS,T,WP",
        [
            "Channelling",
            "Cool",
            "Endurance",
            "Gossip",
            "Intimidate",
            "Language (Magick)",
            "Sleight of Hand",
            "Stealth (Rural)",
        ],
        "Criminal, Menacing, Petty Magic, Witch!",
        "Candles, Chalk, Doll, Pins",
        "Hexer — Brass 1",
    ),
    "Cavalryman": (
        "WS,S,Ag",
        [
            "Animal Care",
            "Charm Animal",
            "Endurance",
            "Language (Battle)",
            "Melee (Basic)",
            "Outdoor Survival",
            "Perception",
            "Ride (Horse)",
        ],
        "Combat Aware, Crack the Whip, Lightning Reflexes, Roughrider",
        "Hand Weapon, Leather Jack, Riding Horse with Saddle and Tack",
        "Horseman — Silver 2",
    ),
    "Guard": (
        "WS,T,Ag",
        [
            "Consume Alcohol",
            "Endurance",
            "Entertain (Storytelling)",
            "Gamble",
            "Gossip",
            "Intuition",
            "Melee (Basic)",
            "Perception",
        ],
        "Diceman, Etiquette (Servants), Strike to Stun, Tenacious",
        "Hand Weapon, Leather Jerkin, Storm Lantern with Oil",
        "Sentry — Silver 1",
    ),
    "Knight": (
        "S,I,Ag",
        [
            "Athletics",
            "Animal Care",
            "Charm Animal",
            "Heal",
            "Lore (Heraldry)",
            "Melee (Cavalry)",
            "Ride (Horse)",
            "Trade (Farrier)",
        ],
        "Etiquette (Any), Roughrider, Sturdy, Warrior Born",
        "Demilance, Leather Jack, Mail Shirt, Riding Horse with Saddle and Tack, Shield, Trade Tools (Farrier)",
        "Squire — Silver 3",
    ),
    "Pit Fighter": (
        "WS,S,T",
        [
            "Athletics",
            "Cool",
            "Dodge",
            "Endurance",
            "Gamble",
            "Intimidate",
            "Melee (Any)",
            "Melee (Fist)",
        ],
        "Dirty Fighter, Infighter, Iron Jaw, Reversal",
        "Bandages, Brass Knuckles, Hand Weapon, Leather Jack",
        "Pugilist — Brass 4",
    ),
    "Protagonist": (
        "WS,T,Ag",
        [
            "Athletics",
            "Dodge",
            "Endurance",
            "Entertain (Taunt)",
            "Gossip",
            "Haggle",
            "Intimidate",
            "Melee (Any)",
        ],
        "Infighter, Dirty Fighting, Menacing, Warrior Born",
        "Brass Knuckles, Hood or Mask, Leather Jack",
        "Braggart — Brass 2",
    ),
    "Slayer": (
        "WS,S,WP",
        [
            "Consume Alcohol",
            "Cool",
            "Dodge",
            "Endurance",
            "Gamble",
            "Heal",
            "Lore (Trolls)",
            "Melee (Basic)",
        ],
        "Dual Wielder, Fearless (Everything), Frenzy, Slayer",
        "Axe, Flask of Spirits, Shame, Tattoos",
        "Troll Slayer — Brass 2",
    ),
    "Soldier": (
        "WS,T,WP",
        [
            "Athletics",
            "Climb",
            "Cool",
            "Dodge",
            "Endurance",
            "Language (Battle)",
            "Melee (Basic)",
            "Play (Drum or Fife)",
        ],
        "Diceman, Marksman, Strong Back, Warrior Born",
        "Hand Weapon (Sword), Leather Armour (uniform)",
        "Recruit — Silver 1",
    ),
    "Warrior Priest": (
        "WS,WP,Fel",
        [
            "Cool",
            "Dodge",
            "Endurance",
            "Heal",
            "Leadership",
            "Lore (Theology)",
            "Melee (Any)",
            "Pray",
        ],
        "Bless (Any), Etiquette (Cultists), Read/Write, Strong-minded",
        "Book (Religion), Leather Jerkin, Religious Symbol, Robes, Weapon (Any)",
        "Novitiate — Brass 2",
    ),
}


def main() -> None:
    out: dict[str, dict] = {}
    for name, (adv, skills, talents_csv, trap, status) in C.items():
        if len(skills) != 8:
            raise SystemExit(f"{name}: expected 8 skills, got {len(skills)}")
        talents = [t.strip() for t in talents_csv.split(",")]
        if len(talents) != 4:
            raise SystemExit(f"{name}: expected 4 talents, got {talents}")
        out[name] = {
            "advance_characteristics": [x.strip() for x in adv.split(",")],
            "skills": skills,
            "talents": talents,
            "trappings": trap,
            "status": status,
            "source": "core",
        }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump({"careers": out, "merge_policy": "by_career_name"}, f, indent=2)
    print("Wrote", OUT, "careers:", len(out))


if __name__ == "__main__":
    main()
